version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/../frontend/build
    networks:
      - movne-network
networks:
  movne-network:
    driver: bridge