version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      - ENVIRONMENT=development
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/movne
    volumes:
      - ./backend:/app
    networks:
      - movne-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - movne-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movne
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movne-network

  ollama:
    container_name: movne-ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - movne-network
    restart: unless-stopped

networks:
  movne-network:
    driver: bridge

volumes:
  app-data:
  postgres_data:
  ollama_data:
  frontend_node_modules:
