[build]
builder = "nixpacks"
watchPatterns = ["backend/**/*.py"]

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure:10"

[deploy.envs]
PYTHON_VERSION = "3.11.0"
