[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 15

[deploy.envs]
PYTHON_VERSION = "3.11.0"
ENVIRONMENT = "production"
OPENAI_API_KEY = "${OPENAI_API_KEY}"