[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt"
watchPatterns = ["backend/**/*.py", "*.py"]

[deploy]
startCommand = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure:10"

[deploy.envs]
PYTHON_VERSION = "3.11.0"
NIXPACKS_PYTHON_VERSION = "3.11.0"
PYTHONPATH = "/workspaces/movne-chatbot-v2"
